-- Two admin correctness fixes that need the database: the product slug, and
-- the ordering of brands and categories.
--
-- ---------------------------------------------------------------------------
-- 1. PRODUCT SLUGS
--
-- `products.slug` is the whole of a product's URL (/product/:slug) and it is
-- UNIQUE. The admin generated it with
--   name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
-- which keeps nothing but ASCII. This store is Arabic first (index.html is
-- lang="ar" dir="rtl") and every product it sells is named in Arabic, so that
-- expression returned the empty string for every product the owner has ever
-- added: the first one saved with an unroutable empty slug and the second hit
-- this unique constraint with a raw Postgres message.
--
-- What the LIVE table actually holds, read before writing this migration:
--
--   118 products
--     1 with a clean Latin slug         ('lv')
--    90 with a single emoji or symbol   ('🐮', '😀', '⚽️', '🐻‍❄️' ...)
--    27 with a single Arabic letter     ('ء', 'ق', 'ش' ...)
--     0 empty
--     0 duplicated, even case insensitively
--     0 with leading or trailing whitespace
--
-- So the owner never met the crash. They found a workaround and have been
-- typing one arbitrary unique character into the slug box for all 118
-- products, the same habit that produced the corrupted brand key 'ل'.
--
-- The generator is fixed in src/lib/slug.ts, which keeps Arabic instead of
-- erasing it, and numbers a duplicate before writing rather than letting the
-- constraint raise. New and edited products need nothing from this migration.
--
-- REWRITING THE 117 EXISTING SLUGS IS NOT DONE HERE, DELIBERATELY. Those are
-- 117 live URLs: bookmarks, WhatsApp and Instagram links, anything indexed.
-- Changing them is the owner's decision and it has been put to them. Section 1c
-- below is the repair, written and ready, commented out. Enable it only on the
-- owner's answer, and read the trade-off in the report before you do.
-- ---------------------------------------------------------------------------

-- 1a. Say what is in the table now, so the next person does not have to go and
--     look. Read only.
do $$
declare
  v_total int;
  v_blank int;
  v_odd int;
  v_dupes int;
begin
  select
    count(*),
    -- The exact NEGATION of the products_slug_not_blank CHECK added below.
    -- Keep the two in step.
    count(*) filter (where slug is null or slug <> btrim(slug) or slug = ''),
    -- Not a slug this store could have generated: anything outside ASCII
    -- alphanumerics, the Arabic block and the separating hyphen.
    count(*) filter (where slug !~ '^[a-z0-9؀-ۿ]+(-[a-z0-9؀-ۿ]+)*$')
  into v_total, v_blank, v_odd
  from public.products;

  select count(*) into v_dupes
  from (select lower(slug) as s from public.products group by 1 having count(*) > 1) d;

  raise notice 'product slugs: % rows, % blank, % not machine generated, % duplicated',
    v_total, v_blank, v_odd, v_dupes;

  -- The CHECK below is added NOT VALID, so the ALTER succeeds whatever is in
  -- the table and a violating row would not be caught here at all. It would be
  -- caught much later and much worse: a NOT VALID check is still evaluated
  -- against the new row version of every future UPDATE of that row, and
  -- place_cod_order() and fulfill_order() both UPDATE products.stock. One
  -- blank or untrimmed slug would therefore freeze that product and fail every
  -- checkout that touches it, weeks after this migration was applied and with
  -- nothing pointing back at it. Stopping now is the cheap failure.
  if v_blank > 0 then
    raise exception 'product slugs: % row(s) have a blank or untrimmed slug. Fix them by hand (or enable section 1c) before adding the constraint', v_blank;
  end if;
end $$;

-- 1b. A blank slug is an unroutable product. The client can no longer produce
--     one, and this makes sure nothing else ever does either. NOT VALID
--     because the audit above has just shown there are no blanks to scan for,
--     so validating would only take a lock on a live table to learn that. It
--     still enforces every INSERT and UPDATE from here on.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'products_slug_not_blank'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_slug_not_blank
      check (slug = btrim(slug) and slug <> '')
      not valid;
  end if;
end $$;

comment on column public.products.slug is
  'The product URL (/product/:slug) and a UNIQUE key. Generated by src/lib/slug.ts, which keeps Arabic: 117 of the 118 rows carry a single hand-typed emoji or Arabic letter from before that existed. Rewriting those changes live URLs and is a decision for the store owner.';

-- 1c. THE REPAIR, DISABLED. Uncomment the whole block to rewrite every slug
--     that the generator could not have produced, from the product's name,
--     numbering collisions. It is idempotent (a second run finds nothing to
--     do) and it never collides: the candidate is checked against the table,
--     not against the rows it has already rewritten. Row by row rather than
--     set based on purpose, because 118 rows run once is not worth the
--     cleverness a single statement would need to dodge the unique index.
--
--     IT CHANGES 117 LIVE URLS. Every existing link to a product breaks. If
--     the owner wants the pretty Arabic URLs without breaking the old ones,
--     that is a redirect table (old slug -> product) and a lookup fallback in
--     ProductDetail, which is a separate piece of work, not this block.
--
-- do $$
-- declare
--   r record;
--   v_base text;
--   v_candidate text;
--   v_n int;
--   v_repaired int := 0;
-- begin
--   for r in
--     select id, name, slug from public.products
--     where slug is null or btrim(slug) = ''
--        or slug !~ '^[a-z0-9؀-ۿ]+(-[a-z0-9؀-ۿ]+)*$'
--     order by created_at, id
--   loop
--     -- The same character class as SLUG_STRIP in src/lib/slug.ts. Keep the
--     -- two in step: ASCII alphanumerics plus the Arabic block, everything
--     -- else is a separator, no leading or trailing hyphen.
--     v_base := btrim(
--       regexp_replace(lower(coalesce(r.name, '')), '[^a-z0-9؀-ۿ]+', '-', 'g'),
--       '-'
--     );
--     -- A name made entirely of emoji still needs a routable URL.
--     if v_base = '' then v_base := 'product'; end if;
--
--     v_candidate := v_base;
--     v_n := 1;
--     while exists (
--       select 1 from public.products where slug = v_candidate and id <> r.id
--     ) loop
--       v_n := v_n + 1;
--       v_candidate := v_base || '-' || v_n;
--     end loop;
--
--     update public.products set slug = v_candidate where id = r.id;
--     raise notice 'product slugs: % -> %', r.slug, v_candidate;
--     v_repaired := v_repaired + 1;
--   end loop;
--
--   raise notice 'product slugs: % row(s) rewritten', v_repaired;
-- end $$;

-- ---------------------------------------------------------------------------
-- 2. ORDERING BRANDS AND CATEGORIES
--
-- Moving a brand or a category up and down fired two independent UPDATEs that
-- traded positions, with both results discarded. A half applied swap leaves
-- the two rows sharing one position, and every later swap of that pair then
-- trades identical numbers: a button that silently does nothing, for good.
--
-- This is admin_reorder_positions() (20260812000000) for the two tables keyed
-- by a text `value` rather than a uuid `id`, and it is the same contract:
-- position becomes the index in the list the client sent, all of it or none.
-- ---------------------------------------------------------------------------
create or replace function public.admin_reorder_positions_by_value(p_table text, p_values text[])
returns integer
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_updated integer;
begin
  if not public.is_admin() then
    raise exception 'admin_reorder_positions_by_value: not authorised'
      using errcode = 'P0001', hint = 'not_admin';
  end if;

  if p_table is null or p_table not in ('brands', 'categories') then
    raise exception 'admin_reorder_positions_by_value: % is not reorderable', coalesce(p_table, '<null>')
      using errcode = 'P0001', hint = 'table_not_reorderable';
  end if;

  if p_values is null or array_length(p_values, 1) is null then
    return 0;
  end if;

  -- WITH ORDINALITY is the ordering: position becomes the index of the key in
  -- the array the client sent. 0 based, matching the rows the storefront
  -- already orders by.
  execute format($q$
    update public.%I t
    set "position" = v.ord - 1
    from (select val, ord from unnest($1::text[]) with ordinality as u(val, ord)) v
    where t.value = v.val
  $q$, p_table)
  using p_values;

  get diagnostics v_updated = row_count;

  -- Every key the caller sent must have matched a row. If one was deleted in
  -- another tab the survivors have just been renumbered around the gap, which
  -- is a DIFFERENT order from the one on screen, and a non-zero row count
  -- would read as success at the call site. Raising rolls the whole statement
  -- back, so the list is either fully applied or untouched.
  if v_updated <> array_length(p_values, 1) then
    raise exception 'admin_reorder_positions_by_value: % of % rows matched in %',
      v_updated, array_length(p_values, 1), p_table
      using errcode = 'P0001', hint = 'reorder_incomplete';
  end if;

  return v_updated;
end;
$$;

comment on function public.admin_reorder_positions_by_value(text, text[]) is
  'Rewrites position 0..n-1 across brands or categories in one statement, keyed by their text `value`. Raises (rolling the statement back) unless every key matched a row. Admin only. Sibling of admin_reorder_positions() for the uuid keyed tables.';

revoke execute on function public.admin_reorder_positions_by_value(text, text[]) from anon, public;
grant execute on function public.admin_reorder_positions_by_value(text, text[]) to authenticated;

-- The admin used to compute max(position) + 1 from the array loaded in the
-- browser, which could be hours old, so a brand added while another tab held
-- a stale list landed on a position another row already had.
--
-- This narrows that window to the gap between two inserts; it does NOT close
-- it. Under READ COMMITTED neither transaction can see the other's uncommitted
-- row, so two truly concurrent inserts still read the same maximum. The cost
-- of that is two rows sharing a position until the next reorder renumbers
-- them, which is not worth a unique index or an advisory lock.
--
-- ponytail: position 0 means "not specified", which is what the column default
-- gives when the client omits it. Nothing in the app inserts a deliberate 0
-- (a new row always goes last), and the reorder RPC above is the only other
-- writer of this column.
create or replace function public.assign_next_position()
returns trigger
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
declare
  v_next int;
begin
  if new."position" is null or new."position" = 0 then
    execute format('select coalesce(max("position") + 1, 0) from public.%I', tg_table_name)
      into v_next;
    new."position" := v_next;
  end if;
  return new;
end;
$$;

comment on function public.assign_next_position() is
  'BEFORE INSERT on brands and categories: puts a new row last when no position was given (null, or the default 0), instead of trusting a maximum computed in the browser. Narrows but does not close the concurrent-insert race: two inserts in flight together still read the same maximum, and the next reorder renumbers them.';

drop trigger if exists brands_assign_next_position on public.brands;
create trigger brands_assign_next_position
  before insert on public.brands
  for each row execute function public.assign_next_position();

drop trigger if exists categories_assign_next_position on public.categories;
create trigger categories_assign_next_position
  before insert on public.categories
  for each row execute function public.assign_next_position();
